services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: oidc_user
      POSTGRES_PASSWORD: oidc_password
      POSTGRES_DB: oidc_db
    ports:
      - "5432:5432"
    networks:
      - oauth-network
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  go-oauth2-server:
    container_name: oauth2-server
    build:
      context: ./go-oauth2-server
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: "your_secure_secret_key"
      PORT: "8080"
    ports:
      - "8080:8080"
    networks:
      - oauth-network
  
  oidc-client:
    container_name: oauth2-client
    build:
      context: ./go-oidc-client
      dockerfile: Dockerfile
    depends_on:
      - go-oauth2-server
    ports:
      - "8081:8080"  # Expose the client's port on a different host port
    environment:
      - CLIENT_ID=client_id
      - CLIENT_SECRET=client_secret
      - REDIRECT_URI=http://localhost:8081/callback
      - AUTH_ENDPOINT=http://auth-server:8080/auth
      - TOKEN_ENDPOINT=http://auth-server:8080/token
    networks:
      - oauth-network

  user-service:
    build:
      context: ./user-service
    ports:
      - "8082:8082"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: oidc_user
      DB_PASSWORD: oidc_password
      DB_NAME: oidc_db
    networks:
      - oauth-network
    depends_on:
      - postgres-db
  
networks:
 oauth-network:
    driver: bridge
